name: Validates certmanager configuration file
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  validate-config:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON prod
        run: jq empty ${{ inputs.config-path }}