name: Docker build and push

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      registry:
        required: true
        type: string
      file:
        default: Dockerfile
        type: string
      runner:
        default: ubuntu-latest
        type: string
      image:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      docker_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push image for ${{ inputs.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ inputs.arch }}
          labels: ${{ steps.meta.outputs.labels }}-${{ inputs.arch }}
          platforms: linux/${{ inputs.arch }}
