name: Builds docker and installs all infra
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      config-path:
        required: true
        type: string
    secrets: inherit
env:
  KUBECONFIG: "config.kubeconfig"
jobs:
  validate-config:
    uses: ./.github/workflows/config.yml
    with:
      config-path: ${{ inputs.config-path }}
  docker: #for GitHub public repositories only see https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    needs:
      - validate-config
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      arch: arm64
      registry: ghcr.io
      file: Dockerfile
      runner: self-hosted
      image: ${{ github.repository }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
  install:
    name: install app
    runs-on: self-hosted
    needs: [ docker ]
    environment:
      name: ${{ inputs.env }}
    env:
      DOCKER_PULL_SECRET: ${{ secrets.DOCKER_PULL_SECRET }}
      DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
      DOCKER_TAG: ${{ needs.docker-arm64.outputs.docker_tag }}
      REV_ID: ${{ github.sha }}
      ENVIRONMENT: ${{ inputs.env }}
      CONFIG_PATH: ${{ inputs.config-path }}
    steps:
      - name: Check if DOCKER_TAG is set
        run: |
          if [ -z "${DOCKER_TAG}" ]; then
            echo "Error: DOCKER_TAG is not set"
            exit 1
          fi
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: 'Install helm'
        uses: 'azure/setup-helm@v4.3.0'
      - name: Kubectl configuration
        run: |
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > "${KUBECONFIG}"
          chmod 600 "${KUBECONFIG}"
      - name: 'Prepare'
        run: 'chmod +x ./infra/scripts/install.sh'
      - name: 'Install certmanager'
        run: './infra/scripts/install.sh certmanager'
      - name: cleanup
        if: always()
        run: |
          rm -f "${KUBECONFIG}"

