name: Update config prod
on:
  workflow_dispatch:
jobs:
  validate-config:
    uses: ./.github/workflows/updateConfig.yml
    with:
      env: prod
      config-path: ./infra/certmanager/files/config-prod.json
    secrets: inherit